package com.huangshihe.mahoutdemo.model;

import com.huangshihe.mahoutdemo.model.base.BaseMovie;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Movie extends BaseMovie<Movie> {
	public static final Movie dao = new Movie();

	public static Movie getMovie(long id){
		return Movie.dao.findFirstByCache("movies", "movie_" + id, "select * from t_movie where id = ?", id);
	}
}
