package com.huangshihe.mahoutdemo.model;

import com.huangshihe.mahoutdemo.model.base.BaseMovie;
import com.huangshihe.mahoutdemo.util.Constants;
import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.CacheName;
import com.jfinal.plugin.ehcache.EvictInterceptor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Movie extends BaseMovie<Movie> {
    public static final Movie dao = new Movie();

    public static Movie getMovie(long id) {
        return Movie.dao.findFirstByCache("movies", "movie_" + id, "select * from t_movie where id = ?", id);
    }

    public static Page getMovies(int pageNum) {
        return Movie.dao.paginateByCache("moviePages", "moviePage" + pageNum, pageNum, Constants.DEFAULT_PAGE_SIZE, "select *", "from t_movie");
    }

//    @Before(EvictInterceptor.class)
//    @CacheName("moviePages")
//    TODO EvictInterceptor can't work
    @Override
    public boolean update(){
//        super.update();
        CacheKit.removeAll("moviePages");
        return super.update();
    }
}
